---
title: "Reproducible documents"
author: "Simon Storgaard"
format: html
---
1. Simon Storgaard
2. Klinisk epidemiologisk afdeling
3. Aarhus university hospital

# Intro
This is the *intro* and it is **short**

# Methods and Results
This *section* is even **shorter**

## Analysis
Okay, *you* need to **stop**

# Discussion
*Come* *on*, **seriously?**

```{r}
2 + 2
```

```{r setup}
#| message: false
#| warning: false
library(tidyverse)
library(NHANES)
nhanes_small <- read_csv(here::here("data/NHANES_small.csv"))
```

```{r}
nhanes_small <- select(nhanes_small, age, sex = gender, bmi, diabetes, phys_active, bp_sys_ave, bp_dia_ave, education)
nhanes_small
```


```{r}
2 + 2
```
# Table of results

```{r}
nhanes_small %>%
  filter(!is.na(diabetes)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  knitr::kable(caption = "mean values of Age and BMI for each education and diabetes status")
```

# Prettier table
```{r}
#| echo: false

nhanes_small %>%
  filter(!is.na(diabetes), !is.na(education)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    # Task 2a.
    mean_age = round(mean_age, 1),
    mean_bmi = round(mean_bmi, 1),
    # Task 2b.
    education = str_to_sentence(education)
  ) %>%
  rename(
    # Task 3.
    "Diabetes Status" = diabetes,
    "Education" = education,
    "Mean Age" = mean_age,
    "Mean BMI" = mean_bmi
  ) %>%
  knitr::kable(caption = "A prettier version of means for each education and diabetes status.")
```
